---

name: Release Drafter

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@b853a4c92ff8c8de0356b86c020abb3c31cd0715
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
